name: CD-Prod

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying to PROD... API Key: ${{ secrets.PROD_API_KEY }}"
